prometheus:
  prometheusSpec:
    retention: 1d   # keep metrics for 1 day
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi   # small PVC, saves space
