FROM node:20-alpine

WORKDIR /app

# Copy only server package.json and lock file
COPY server/AMT_be-main/package*.json ./

# Install dependencies (production only)
RUN npm install --production

# Copy the rest of the server code
COPY server/AMT_be-main ./

EXPOSE 3001

CMD ["npm", "start"]
