FROM node:20-alpine as builder
WORKDIR /app
COPY AMT_fe-main/package*.json ./
RUN npm install
COPY AMT_fe-main/ ./
RUN npm run build
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
