FROM node:20-alpine

WORKDIR /app

# Copy only server package.json and lock file
COPY apps/app1/server/AMT_be-main/package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the server code
COPY apps/app1/server/AMT_be-main ./

EXPOSE 3001

CMD ["npm", "start"]
