apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prod
  namespace: argocd
spec:
  project: default
  # 👇 Use multi-sources so Helm can read values outside the chart dir
  sources:
    - repoURL: https://github.com/yogeshhome/my-hosting-server.git
      targetRevision: main
      path: k3s/monitoring/base/chart
      helm:
        valueFiles:
          - $values/k3s/monitoring/overlays/prod/prometheus-values-prod.yaml
    - repoURL: https://github.com/yogeshhome/my-hosting-server.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
