apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-client
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-client
  template:
    metadata:
      labels:
        app: app1-client
    spec:
      volumes:
        - name: run
          emptyDir: {}
        - name: cache
          emptyDir: {}

      initContainers:
        - name: fix-nginx-perms
          image: ghcr.io/yogeshhome/app1-client:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /var/run /var/cache/nginx/client_temp && \
              chown -R 101:101 /var/run /var/cache/nginx
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: run
              mountPath: /var/run
            - name: cache
              mountPath: /var/cache/nginx

      containers:
        - name: app1-client
          image: ghcr.io/yogeshhome/app1-client:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: run
              mountPath: /var/run
            - name: cache
              mountPath: /var/cache/nginx
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: app1-client
  namespace: production
spec:
  selector:
    app: app1-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
