apiVersion: v1
kind: Service
metadata:
  name: app1-client
  namespace: production
spec:
  selector:
    app: app1-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
