apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app1-mongo
  namespace: production
spec:
  serviceName: app1-mongo
  replicas: 1
  selector:
    matchLabels:
      app: app1-mongo
  template:
    metadata:
      labels:
        app: app1-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "Kskarthik21"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi