apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-server
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-server
  template:
    metadata:
      labels:
        app: app1-server
    spec:
      containers:
        - name: app1-server
          image: ghcr.io/yogeshhome/app1-server:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_URL
              value: "mongodb://root:Kskarthik21@app1-mongo:27017/Inventary?authSource=admin&retryWrites=true&w=majority"
            - name: DB_NAME
              value: "Inventary"
            - name: JWT_EXPIRE
              value: "100m"
            - name: JWT_SECRET
              value: "sjfnajsfnjsafnla8989ffi9"
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
      imagePullSecrets:
        - name: ghcr-secret
