apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-server
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-server
  template:
    metadata:
      labels:
        app: app1-server
    spec:
      containers:
        - name: app1-server
          image: ghcr.io/yogeshhome/app1-server:007be6a3c323fab21298c524c825fd7b26a6857f
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: app1-config
            - secretRef:
                name: server-secret   # ✅ corrected secret name
          resources:
            requests:
              cpu: "250m"       # reduced to 0.25 core
              memory: "512Mi"   # reduced to 0.5 GB RAM
            limits:
              cpu: "500m"       # max 0.5 core
              memory: "1Gi"     # max 1 GB RAM
          # Probes disabled until /health endpoint exists
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3001
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3001
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-secret
