name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Client
      - name: Build and push client image
        run: |
          docker build -f apps/app1/Dockerfile.client -t yogeshhome/app1:client-${{ github.sha }} ./apps/app1
          docker tag yogeshhome/app1:client-${{ github.sha }} yogeshhome/app1:client-latest
          docker push yogeshhome/app1:client-${{ github.sha }}
          docker push yogeshhome/app1:client-latest

      # Build & Push Server
      - name: Build and push server image
        run: |
          docker build -f apps/app1/Dockerfile.server -t yogeshhome/app1:server-${{ github.sha }} ./apps/app1
          docker tag yogeshhome/app1:server-${{ github.sha }} yogeshhome/app1:server-latest
          docker push yogeshhome/app1:server-${{ github.sha }}
          docker push yogeshhome/app1:server-latest
